const i18n={
  pt:{
    'nav.product':'Produto','nav.flow':'Como funciona','nav.features':'Recursos','nav.security':'Segurança','nav.cta':'Quero testar',
    'hero.eyebrow':'Lead Intelligence para operações que querem crescer','hero.title':'Pare de perder leads.<br><span>Transforme interesse em oportunidade.</span>','hero.text':'O JKDD Leads recebe contatos, organiza dados, elimina duplicidades, qualifica, pontua e encaminha cada lead para o próximo passo certo — com rastreabilidade e governança.','hero.primary':'Solicitar acesso antecipado','hero.secondary':'Ver como funciona',
    'trust.cost':'Zero dependência paga no MVP','trust.audit':'Regras auditáveis','trust.multi':'Multi-tenant desde o início',
    'mock.hello':'Visão comercial','mock.title':'Lead Inbox','mock.new':'Novos','mock.qualified':'Qualificados','mock.hot':'Hot Leads',
    'metrics.record':'registro canônico por lead','metrics.core':'etapas centrais no MVP','metrics.audit':'decisões rastreáveis','metrics.paid':'IA paga obrigatória',
    'product.kicker':'O problema','product.title':'Leads chegam de todos os lados.<br><span>O caos não precisa chegar junto.</span>','product.text':'Formulários, indicações, campanhas, WhatsApp, redes sociais e parceiros geram contatos com formatos diferentes. O JKDD Leads cria uma camada única para transformar essa entrada em informação comercial utilizável.',
    'pain.dup.title':'Duplicidade','pain.dup.text':'O mesmo contato entrando várias vezes e confundindo o time.','pain.slow.title':'Resposta lenta','pain.slow.text':'Lead quente esfria enquanto alguém decide quem deve atender.','pain.blind.title':'Falta de contexto','pain.blind.text':'Sem origem, score ou histórico, todo lead parece igual.','pain.measure.title':'Sem medição','pain.measure.text':'Sem atribuição clara, fica difícil saber o que realmente gera negócio.',
    'flow.kicker':'Vertical slice do MVP','flow.title':'Da entrada ao handoff comercial,<br><span>uma linha de produção de leads.</span>','flow.acquire':'Recebe leads de fontes conectadas.','flow.normalize':'Padroniza telefone, nome, origem e atributos.','flow.dedup':'Procura correspondências antes de criar outro registro.','flow.qualify':'Aplica critérios objetivos de qualificação.','flow.score':'Prioriza leads com regras auditáveis.','flow.route':'Encaminha para o destino comercial correto.',
    'features.kicker':'O que entra no núcleo','features.title':'Feito para organizar crescimento.<br><span>Não para virar mais um CRM pesado.</span>','features.inbox.title':'Lead Inbox inteligente','features.inbox.text':'Uma fila operacional com prioridade, origem, score, status e próximos passos visíveis.','features.score.title':'Scoring auditável','features.score.text':'Começa determinístico. Cada ponto precisa ter explicação.','features.dedup.title':'Deduplicação','features.dedup.text':'Um lead, um registro canônico, múltiplas visualizações.','features.route.title':'Routing','features.route.text':'Regras para enviar cada lead ao time, produto ou CRM certo.','features.ai.title':'AI-ready, sem AI obrigatória','features.ai.text':'IA poderá apoiar classificação e resumo, mas nunca vira Source of Truth silenciosamente.','features.measure.title':'Attribution & Measure','features.measure.text':'Entenda de onde o lead veio, o que aconteceu com ele e quais fontes entregam melhor qualidade.',
    'security.kicker':'Foundation-first','security.title':'Segurança não entra depois.<br><span>Ela define a arquitetura.</span>','security.text':'JKDD Leads nasce multi-tenant e reutiliza contratos compartilhados da JKDD TECH Foundation para identidade, sessão, empresas, permissões, RLS, auditoria e demais capacidades comuns.','security.reuse':'REUSE BEFORE BUILD',
    'eco.kicker':'Ecossistema JKDD TECH','eco.title':'O lead pode nascer em um produto.<br><span>Mas só existe um registro canônico.</span>','eco.origin':'Pode originar um contato','eco.core':'Possui o Lead canônico','eco.crm':'Consome e avança a venda',
    'cta.kicker':'Early access','cta.title':'Quer ver seus leads<br><span>trabalhando para você?</span>','cta.text':'Entre na lista de teste do JKDD Leads. Esta Preview V1 ainda não envia dados para backend.','form.name':'Nome','form.company':'Empresa','form.contact':'E-mail ou telefone','form.submit':'Quero testar o JKDD Leads','form.note':'PREVIEW: dados ficam somente neste navegador até a integração com o intake canônico.','footer.tag':'ACQUIRE → NORMALIZE → QUALIFY → SCORE → ROUTE → MEASURE','footer.soon':'em breve'
  },
  en:{
    'nav.product':'Product','nav.flow':'How it works','nav.features':'Features','nav.security':'Security','nav.cta':'Get early access',
    'hero.eyebrow':'Lead Intelligence for teams built to grow','hero.title':'Stop losing leads.<br><span>Turn interest into opportunity.</span>','hero.text':'JKDD Leads receives contacts, organizes data, removes duplicates, qualifies, scores and routes every lead to the right next step — with traceability and governance.','hero.primary':'Request early access','hero.secondary':'See how it works',
    'trust.cost':'No paid dependency required for MVP','trust.audit':'Auditable rules','trust.multi':'Multi-tenant from day one',
    'mock.hello':'Sales view','mock.title':'Lead Inbox','mock.new':'New','mock.qualified':'Qualified','mock.hot':'Hot Leads',
    'metrics.record':'canonical record per lead','metrics.core':'core MVP stages','metrics.audit':'traceable decisions','metrics.paid':'mandatory paid AI',
    'product.kicker':'The problem','product.title':'Leads come from everywhere.<br><span>The chaos does not have to.</span>','product.text':'Forms, referrals, campaigns, WhatsApp, social media and partners create contacts in different formats. JKDD Leads creates one operational layer that turns incoming interest into usable sales information.',
    'pain.dup.title':'Duplicates','pain.dup.text':'The same contact enters multiple times and confuses the team.','pain.slow.title':'Slow response','pain.slow.text':'Hot leads cool down while someone decides who should respond.','pain.blind.title':'No context','pain.blind.text':'Without source, score or history, every lead looks the same.','pain.measure.title':'No measurement','pain.measure.text':'Without clear attribution, it is hard to know what actually creates business.',
    'flow.kicker':'MVP vertical slice','flow.title':'From intake to sales handoff,<br><span>a production line for leads.</span>','flow.acquire':'Receives leads from connected sources.','flow.normalize':'Standardizes phone, name, source and attributes.','flow.dedup':'Checks for matches before another record is created.','flow.qualify':'Applies objective qualification criteria.','flow.score':'Prioritizes leads with auditable rules.','flow.route':'Routes each lead to the right commercial destination.',
    'features.kicker':'What belongs in the core','features.title':'Built to organize growth.<br><span>Not to become another heavy CRM.</span>','features.inbox.title':'Smart Lead Inbox','features.inbox.text':'An operational queue with priority, source, score, status and next steps visible.','features.score.title':'Auditable scoring','features.score.text':'Starts deterministic. Every point should have an explanation.','features.dedup.title':'Deduplication','features.dedup.text':'One lead, one canonical record, multiple product views.','features.route.title':'Routing','features.route.text':'Rules that send each lead to the right team, product or CRM.','features.ai.title':'AI-ready, not AI-dependent','features.ai.text':'AI may assist classification and summaries, but it never silently becomes Source of Truth.','features.measure.title':'Attribution & Measure','features.measure.text':'Know where each lead came from, what happened next and which sources deliver better quality.',
    'security.kicker':'Foundation-first','security.title':'Security is not added later.<br><span>It shapes the architecture.</span>','security.text':'JKDD Leads is multi-tenant from day one and reuses JKDD TECH Foundation contracts for identity, sessions, companies, permissions, RLS, audit and shared capabilities.','security.reuse':'REUSE BEFORE BUILD',
    'eco.kicker':'JKDD TECH ecosystem','eco.title':'A lead can originate in one product.<br><span>But there is only one canonical record.</span>','eco.origin':'May originate a contact','eco.core':'Owns the canonical Lead','eco.crm':'Consumes and advances the sale',
    'cta.kicker':'Early access','cta.title':'Ready to make your leads<br><span>work for you?</span>','cta.text':'Join the JKDD Leads test list. This Preview V1 does not send data to a backend yet.','form.name':'Name','form.company':'Company','form.contact':'Email or phone','form.submit':'I want to test JKDD Leads','form.note':'PREVIEW: data stays in this browser until canonical intake integration is enabled.','footer.tag':'ACQUIRE → NORMALIZE → QUALIFY → SCORE → ROUTE → MEASURE','footer.soon':'coming soon'
  }
};
let lang=localStorage.getItem('jkdd-leads-lang')||'pt';
const applyLang=()=>{document.documentElement.lang=lang==='pt'?'pt-BR':'en';document.querySelectorAll('[data-i18n]').forEach(el=>{const value=i18n[lang][el.dataset.i18n];if(value!==undefined)el.innerHTML=value});document.getElementById('langBtn').textContent=lang==='pt'?'EN':'PT';localStorage.setItem('jkdd-leads-lang',lang)};
document.getElementById('langBtn').addEventListener('click',()=>{lang=lang==='pt'?'en':'pt';applyLang()});applyLang();
const menuBtn=document.getElementById('menuBtn'),navLinks=document.getElementById('navLinks');menuBtn.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open))});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.getElementById('year').textContent=new Date().getFullYear();
const form=document.getElementById('earlyForm'),toast=document.getElementById('toast');form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));const records=JSON.parse(localStorage.getItem('jkdd-leads-preview-requests')||'[]');records.push({...data,createdAt:new Date().toISOString(),preview:true});localStorage.setItem('jkdd-leads-preview-requests',JSON.stringify(records));form.classList.add('success');form.reset();toast.textContent=lang==='pt'?'Preview registrada neste navegador. Nenhum dado foi enviado para servidor.':'Preview saved in this browser. No data was sent to a server.';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),4200)});
